### ISSUE TITLE
Could this be used for content-aware filling?

### ISSUE THREAD

**Issue by WindowsNT** [davidirobinson/image-retargeting#2]
I'm about to try it in OpenCV in windows, seems interesting. Is there a possiblity that it may be used for content-aware filling?

**Comment by davidirobinson** [comment]
@WindowsNT This algorithm serves a slightly different purpose to content-aware filling. I suggest taking a look at something like this https://docs.opencv.org/4.5.1/df/d3d/tutorial_py_inpainting.html.
